# Generated by Django 4.2.17 on 2025-01-07 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clipapp', '0003_usertestimonial_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertestimonial',
            name='occupation',
            field=models.TextField(default=5),
            preserve_default=False,
        ),
    ]
